### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by AndyPark20** [AndyPark20/driving-game#2]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x]  Set background color to green.
- [x]  Find a car image and make sure that the color for the car matches with the background color to the screen.
- [x]  Create a container div and a div for the IMG element. 
- [x]  Set absolute and relative positions to the corresponding elements.
- [x]  Check the final visual effects.
- [x]  Make any changes to CSS or HTML if necessary.

![image](https://user-images.githubusercontent.com/69870979/101949132-fb805180-3ba7-11eb-8c2c-3d83a6aceff3.png)
