### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by AndyPark20** [AndyPark20/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x]  Dom query the IMG element that you want to select.
- [x]  create an object called myCar that will store a property name "directions" that will store which way the car is currently facing.
- [x]  Create an AddEventListener on the document.
- [x]  Create a function (named or anonymous) that when "keydown" is initiated it will store the direction into the myCar object.
- [x]  When "keydown" is initiated, the car image will rotate according to the set given keyArrow direction by using transform and transition property in the CSS.
- [x]  Check to see if all functionality is working properly. 
- [x]  Fix any bugs that are present.

![image](https://user-images.githubusercontent.com/69870979/101949197-105ce500-3ba8-11eb-9289-7c354225ee24.png)
