### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by AndyPark20** [AndyPark20/driving-game#4]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x]  Create x and y property in the myCar Object.
- [x]  Create a setInterval() function set at 16 milliseconds and set the variable to null.
- [x]  If spacebar has been pressed, increment x or y values which will then be translated into px to move the car on position absolute.
- [x]  Verify that the x and y values are stored once moveCar function has been executed. 
- [x] Verify that all functions are working correctly and there are no bugs.
