### ISSUE TITLE
User can stop their car

### ISSUE THREAD

**Issue by AndyPark20** [AndyPark20/driving-game#5]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] Create a Boolean expression if the car is currently stopped or in motion.
- [x] Create an expression if the car is moving and the user keydown spacebar, the car will stop. 
- [x] Verify that the x and y coordinates are still recorded on the myCar object.
- [x] Make sure that there are no bugs and unnecessary CSS styling is visible.
