### ISSUE TITLE
User can steer their car

### ISSUE THREAD

**Issue by AndyPark20** [AndyPark20/driving-game#6]
## 💰 Motivation

Our game needs MAXIMUM realism to be immersive 😂.

## 📐 Plan

Change the car's location based on which direction it is facing.

## ✅ Task List

- [x]  Add an expression if both spacebar and the arrowKeys are pressed the car will move according to the directed key.
- [x]  When the car is moving, myCar object should constantly get an update for both x and y coordinate until the user stops the 
        car.
- [x]  Check  to see if there are any bugs while driving the car in different direction.
- [x]  Clear and omit any unnecessary CSS and Js files that are not needed 

![image](https://user-images.githubusercontent.com/69870979/101949294-3a160c00-3ba8-11eb-8f2c-d5a459c20890.png)
